### PR TITLE
bf and dad idle animation at the very beginning of a song

### PR DESCRIPTION
**Pull request by Burgerballs**
a very minor fix but gdjflkgdjflkgjdlgkdjfglkdjfg

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]
I've seen it happen in vanilla FNF iirc, so yeah

**Comment by BeastlyGhost** [comment]
use `charactersDance(curBeat)` instead

**Comment by voiddevv** [comment]
how is this a problem?

**Comment by Burgerballs** [comment]
> how is this a problem?

It looks jarring compared to the base game and other engines

**Pull request merged**
